---
# tasks file for panxatony.omd-client

- name: be sure xinetd is installed
  yum: name=xinetd state=installed
  become: yes
  become_user: root
  tags:
    - omd-client

- name: enable xinetd
  service: name=xinetd enabled=yes
  become: yes
  become_user: root
  tags:
    - omd-client

- name: copy check_mk rpm 
  copy: src={{ omdistro_client_rpm }} dest={{ omdistro_rpm_tmp_folder }}/{{ omdistro_client_rpm }} mode=0644 
  become: yes
  become_user: root
  tags:
    - omd-client

- name: install check_mk rpm package
  yum: name={{ omdistro_rpm_tmp_folder }}/{{ omdistro_client_rpm }} state=present
  notify:
    - restart xinetd
  become: yes
  become_user: root
  tags:
    - omd-client

- name: Make sure basic ports are opened in the firewall
  firewalld: port="{{ item }}" permanent=true state=enabled
  with_items: omd_firewall_allow_ports
  when: omd_firewall_allow_ports is defined
  when: omd_activate_firewall == true
  notify:
    - restart firewalld
  become: yes
  become_user: root
  tags:
    - omd-client

- name: restart services
  service: name="{{ item }}" state=restarted
  with_items:
    - xinetd
    - firewalld
  become: yes
  become_user: root
  tags:
    - omd-client


- name: create wato file
  file: path=/opt/omd/sites/{{ omdistro_site }}/etc/check_mk/conf.d/wato/hosts.mk owner={{ omdistro_site }} group={{ omdistro_site }} mode=0644
  become: yes
  become_user: root
  tags:
    - omd-client

- name: Check if add_to_check_mk is already copied to {{ omdistro_server }}.
  delegate_to: "{{ item }}"
  with_items:
    - "{{ omdistro_server }}"
  stat: path=/usr/local/bin/add_to_check_mk.sh
  register: omd_check_mk_file
  become: yes
  become_user: root
  tags:
    - omd-client

- name: copy add_to_check_mk.sh script to omd {{ omdistro_server }}
  copy: src=add_to_check_mk.sh dest=/usr/local/bin/add_to_check_mk.sh mode=0755 
  #when: (omd_check_mk_file.stat.exists == false)
  become: yes
  delegate_to: "{{ item }}"
  with_items:
    - "{{ omdistro_server }}"
  become: yes
  become_user: root
  tags:
    - omd-client

- name: add client to omd
  #command: /usr/local/bin/add_to_check_mk.sh -s {{ omdistro_site }} -h {{ ansible_nodename }} -f {{ omd_client_folder }}
  command: /usr/local/bin/add_to_check_mk.sh -s {{ omdistro_site }} -h {{ ansible_nodename }}
  delegate_to: "{{ item }}"
  with_items:
    - "{{ omdistro_server }}"
  become: yes
  become_user: root
  tags:
    - omd-client