---
# handlers file for panxatony.omd-client

- name: restart xinetd
  service: 
    name: xinetd
    state: restarted
  become: yes
  become_user: root

- name: restart firewalld
  service:
    name: firewalld
    state: restarted
  become: yes
  become_user: root